services:
  reverse-proxy:

    image: traefik:v2.5

    command:
      - --api.insecure=true # Enables web ui
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure # redirect http to https
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    ports:
      - "80:80"
      - "443:443"
      # web ui
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/:/etc/traefik/dynamic/
      - ../cert/:/etc/certs/

  auth_server:
    image: auth_server:latest
    build: 
        context: auth_server
        dockerfile: Dockerfile
    container_name: auth_server
    volumes:
      - ./config/auth_server/auth_config.toml:/server/auth_config.toml:rw
      - ../cert/:/server/cert/
    depends_on:
      - mongo
      - mail-sender
    environment:
      RUST_BACKTRACE: 1
    labels:
      - "traefik.http.routers.auth.rule=Host(`localhost`) && (PathPrefix(`/auth`) || PathPrefix(`/admin`))"
      - "traefik.http.services.auth.loadbalancer.server.scheme=http"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls=true"

  admin_panel:
    image: admin_panel:latest
    build: 
        context: client
        dockerfile: Dockerfile
    container_name: admin_panel
    labels:
      - "traefik.http.routers.panel.rule=Host(`localhost`)"
      - "traefik.http.services.panel.loadbalancer.server.scheme=http"
      - "traefik.http.services.panel.loadbalancer.server.port=80"
      - "traefik.http.routers.panel.entrypoints=websecure"
      - "traefik.http.routers.panel.tls=true"

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mail-sender:
    image: tozd/postfix:alpine-312
    container_name: mail-sender
    privileged: true
    volumes:
      - ./config/postfix/init:/etc/service/postfix/run.initialization:rw


  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin


  




