[package]
name = "auth_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = { version = "0.10.0-rc.4", features = ["smtp-transport", "builder"] }
tokio = "1.12.0"
anyhow = "1.0"
toml = "0.5.8"
serde = {version = "1.0.130"}
serde_derive = "*"
tracing = "0.1.29"
tracing-subscriber = "0.3.1"
actix-web = "4.0.0-beta.12"
mongodb = "2.0.1"
sodiumoxide = "0.2.7"
#tracing-actix-web = "0.5.0-beta.2"
jsonwebtoken = "7.2.0"
chrono = "0.4.19"
thiserror = "1.0.30"
futures-util = "0.3.17"
actix-service = "2.0.1"
futures = "0.3.17"
notify = "4.0.17"
actix-web-httpauth = "0.6.0-beta.4"
